apiVersion: v1
kind: Namespace
metadata:
  name: cert-status-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-checker-script
  namespace: cert-status-app
data:
  check-certs.sh: |
    #!/bin/bash
    OUTPUT_FILE="/var/www/html/certs.html"
    echo "Starting certificate analysis..."
    
    # Create basic HTML
    cat > "$OUTPUT_FILE" << 'EOF'
    <!DOCTYPE html>
    <html>
    <head>
        <title>Certificate Monitor</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; }
            table { border-collapse: collapse; width: 100%; }
            th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
            th { background-color: #f2f2f2; }
        </style>
    </head>
    <body>
        <h1>Certificate Monitor</h1>
        <p>Generated: $(date)</p>
        <table>
            <tr>
                <th>Namespace</th>
                <th>Certificate</th>
                <th>Created</th>
                <th>Expires</th>
                <th>Days Left</th>
            </tr>
    EOF
    
    # Check certificates in namespaces
    for namespace in openshift-etcd openshift-kube-apiserver openshift-authentication openshift-image-registry kube-system openshift-node; do
        echo "Checking $namespace..."
        # Get TLS secrets and process them
        oc -n "$namespace" get secrets --no-headers -o custom-columns="NAME:.metadata.name,TYPE:.type" 2>/dev/null | grep "kubernetes.io/tls" | while IFS= read -r line; do
            if [[ -z "$line" ]]; then continue; fi
            name=$(echo "$line" | awk '{print $1}')
            echo "Processing certificate: $name"
            
            # Get certificate data
            cert_data=$(oc -n "$namespace" get secret "$name" -o go-template='{{index .data "tls.crt"}}' 2>/dev/null)
            if [[ -z "$cert_data" ]]; then
                cert_data=$(oc -n "$namespace" get secret "$name" -o go-template='{{index .data "ca.crt"}}' 2>/dev/null)
            fi
            
            if [[ -n "$cert_data" ]]; then
                cert_decoded=$(echo "$cert_data" | base64 -d 2>/dev/null)
                if [[ -n "$cert_decoded" ]]; then
                    not_before=$(echo "$cert_decoded" | openssl x509 -noout -startdate 2>/dev/null | cut -d= -f2)
                    not_after=$(echo "$cert_decoded" | openssl x509 -noout -enddate 2>/dev/null | cut -d= -f2)
                    
                    if [[ -n "$not_before" && -n "$not_after" ]]; then
                        before_epoch=$(date -j -f "%b %d %H:%M:%S %Y %Z" "$not_before" +%s 2>/dev/null)
                        after_epoch=$(date -j -f "%b %d %H:%M:%S %Y %Z" "$not_after" +%s 2>/dev/null)
                        
                        if [[ -z "$before_epoch" || -z "$after_epoch" ]]; then
                            before_epoch=$(date -j -f "%b  %d %H:%M:%S %Y %Z" "$not_before" +%s 2>/dev/null)
                            after_epoch=$(date -j -f "%b  %d %H:%M:%S %Y %Z" "$not_after" +%s 2>/dev/null)
                        fi
                        
                        if [[ -n "$before_epoch" && -n "$after_epoch" ]]; then
                            created_date=$(date -j -f "%b %d %H:%M:%S %Y %Z" "$not_before" "+%m/%d/%Y" 2>/dev/null || date -j -f "%b  %d %H:%M:%S %Y %Z" "$not_before" "+%m/%d/%Y" 2>/dev/null || echo "Unknown")
                            expiry_date=$(date -j -f "%b %d %H:%M:%S %Y %Z" "$not_after" "+%m/%d/%Y" 2>/dev/null || date -j -f "%b  %d %H:%M:%S %Y %Z" "$not_after" "+%m/%d/%Y" 2>/dev/null || echo "Unknown")
                            
                            current_epoch=$(date +%s)
                            days_until_expiry=$(( (after_epoch - current_epoch) / 86400 ))
                            
                            echo "<tr><td>$namespace</td><td>$name</td><td>$created_date</td><td>$expiry_date</td><td>$days_until_expiry</td></tr>" >> "$OUTPUT_FILE"
                            echo "Added certificate: $name"
                        fi
                    fi
                fi
            fi
        done
    done
    
    # Close HTML
    cat >> "$OUTPUT_FILE" << 'EOF'
        </table>
    </body>
    </html>
    EOF
    
    echo "Certificate status HTML generated at: $OUTPUT_FILE"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-status-app
  namespace: cert-status-app
  labels:
    app: cert-status-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-status-monitor
  template:
    metadata:
      labels:
        app: cert-status-monitor
    spec:
      serviceAccountName: cert-monitor-sa
      containers:
      - name: httpd
        image: registry.redhat.io/rhel8/httpd-24:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: html-content
          mountPath: /var/www/html
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      - name: cert-updater
        image: registry.redhat.io/openshift4/ose-cli:latest
        command: ["/bin/bash"]
        args: ["-c", "while true; do /scripts/check-certs.sh; sleep 300; done"]
        volumeMounts:
        - name: html-content
          mountPath: /var/www/html
        - name: cert-checker-script
          mountPath: /scripts
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: html-content
        emptyDir: {}
      - name: cert-checker-script
        configMap:
          name: cert-checker-script
          defaultMode: 0755
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-monitor-sa
  namespace: cert-status-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-monitor-role
rules:
- apiGroups: [""]
  resources: ["secrets", "namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-monitor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-monitor-role
subjects:
- kind: ServiceAccount
  name: cert-monitor-sa
  namespace: cert-status-app
---
apiVersion: v1
kind: Service
metadata:
  name: cert-status-service
  namespace: cert-status-app
  labels:
    app: cert-status-monitor
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: cert-status-monitor
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cert-status-route
  namespace: cert-status-app
  labels:
    app: cert-status-monitor
spec:
  to:
    kind: Service
    name: cert-status-service
  port:
    targetPort: 8080
