---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-checker-script
  namespace: cert-status-app
data:
  check-certs.sh: |
    #!/bin/bash
    # Certificate status checker for hosted clusters (shows actual visible certificates)
    
    OUTPUT_FILE="/var/www/html/certs.html"
    
    # Function to get certificate info and convert to HTML
    generate_html_output() {
        cat > "$OUTPUT_FILE" << 'EOF'
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>OpenShift Certificate Status Monitor</title>
        <style>
            body {
                font-family: 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;
                margin: 0;
                padding: 20px;
                background: linear-gradient(135deg, #2c3e50 0%, #34495e 100%);
                color: #ecf0f1;
                line-height: 1.6;
            }
            .container {
                max-width: 1400px;
                margin: 0 auto;
                background: rgba(0,0,0,0.7);
                padding: 30px;
                border-radius: 15px;
                box-shadow: 0 10px 30px rgba(0,0,0,0.5);
            }
            .header {
                text-align: center;
                margin-bottom: 30px;
                border-bottom: 2px solid #3498db;
                padding-bottom: 20px;
            }
            .header h1 {
                color: #3498db;
                font-size: 2.5em;
                margin: 0;
            }
            .section {
                margin: 30px 0;
                padding: 20px;
                background: rgba(52, 73, 94, 0.3);
                border-radius: 10px;
                border-left: 4px solid #3498db;
            }
            .section h2 {
                color: #e74c3c;
                margin-top: 0;
                font-size: 1.4em;
            }
            .cert-table {
                width: 100%;
                border-collapse: collapse;
                margin: 15px 0;
                background: rgba(0,0,0,0.4);
                border-radius: 8px;
                overflow: hidden;
                font-size: 0.9em;
            }
            .cert-table th {
                background: #2c3e50;
                color: #ecf0f1;
                padding: 10px 8px;
                text-align: left;
                font-weight: bold;
            }
            .cert-table td {
                padding: 8px;
                border-bottom: 1px solid rgba(255,255,255,0.1);
                word-wrap: break-word;
                max-width: 200px;
            }
            .status-good { background: rgba(46, 204, 113, 0.2); }
            .status-warning { background: rgba(243, 156, 18, 0.2); }
            .status-critical { background: rgba(231, 76, 60, 0.2); }
            .info-box {
                background: rgba(52, 152, 219, 0.2);
                border-left: 4px solid #3498db;
                padding: 15px;
                margin: 15px 0;
                border-radius: 5px;
            }
            .alert-box {
                background: rgba(231, 76, 60, 0.2);
                border-left: 4px solid #e74c3c;
                padding: 15px;
                margin: 15px 0;
                border-radius: 5px;
            }
            .success-box {
                background: rgba(46, 204, 113, 0.2);
                border-left: 4px solid #2ecc71;
                padding: 15px;
                margin: 15px 0;
                border-radius: 5px;
            }
            .refresh-info {
                text-align: center;
                margin-top: 30px;
                color: #95a5a6;
                font-style: italic;
            }
            .metadata {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
                gap: 15px;
                margin: 20px 0;
            }
            .meta-item {
                background: rgba(0,0,0,0.3);
                padding: 15px;
                border-radius: 8px;
            }
            .meta-label {
                color: #3498db;
                font-weight: bold;
                display: block;
            }
            .nav-links {
                text-align: center;
                margin: 30px 0;
            }
            .nav-links a {
                display: inline-block;
                margin: 10px;
                padding: 12px 24px;
                background: rgba(52, 152, 219, 0.3);
                color: #ecf0f1;
                text-decoration: none;
                border-radius: 25px;
                transition: all 0.3s ease;
                border: 1px solid #3498db;
            }
            .nav-links a:hover {
                background: rgba(52, 152, 219, 0.5);
                transform: translateY(-2px);
            }
            .cert-summary {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                gap: 15px;
                margin: 20px 0;
            }
            .summary-card {
                background: rgba(0,0,0,0.3);
                padding: 20px;
                border-radius: 8px;
                text-align: center;
            }
            .summary-card h3 {
                margin: 0 0 10px 0;
                color: #3498db;
            }
            .summary-count {
                font-size: 2em;
                font-weight: bold;
                margin: 10px 0;
            }
        </style>
        <script>
            // Auto-refresh every 60 seconds
            setTimeout(function() {
                window.location.reload();
            }, 60000);
        </script>
    </head>
    <body>
        <div class="container">
            <div class="header">
                <h1>🔐 OpenShift Certificate Monitor</h1>
                <div class="metadata">
                    <div class="meta-item">
                        <span class="meta-label">Generated:</span>
                        <span>$(date)</span>
                    </div>
                    <div class="meta-item">
                        <span class="meta-label">Cluster:</span>
                        <span>$(oc whoami --show-server 2>/dev/null | sed 's/https:\/\///' | cut -d':' -f1 || echo 'my-hosted-cluster')</span>
                    </div>
                    <div class="meta-item">
                        <span class="meta-label">User:</span>
                        <span>$(oc whoami 2>/dev/null || echo 'system:serviceaccount')</span>
                    </div>
                    <div class="meta-item">
                        <span class="meta-label">Context:</span>
                        <span>Hosted Cluster Worker Certificates</span>
                    </div>
                </div>
            </div>

            <div class="nav-links">
                <a href="index.html">🏠 Home</a>
                <a href="certs.html">🔐 Certificates</a>
                <a href="javascript:window.location.reload()">🔄 Refresh</a>
            </div>
    EOF

        # Get certificate summary
        get_certificate_summary

        # Check important certificate namespaces
        check_namespace_certs "openshift-ingress" "Ingress Router Certificates"
        check_namespace_certs "openshift-monitoring" "Monitoring & Metrics Certificates"
        check_namespace_certs "openshift-console" "Console Certificates" 
        check_namespace_certs "openshift-service-ca" "Service CA Certificates"
        check_namespace_certs "openshift-ovn-kubernetes" "Network Certificates"
        check_namespace_certs "openshift-machine-config-operator" "Machine Config Certificates"

        # Add information about hosted cluster certificate architecture
        cat >> "$OUTPUT_FILE" << 'EOF'
            <div class="section">
                <h2>📋 Hosted Cluster Certificate Architecture</h2>
                <div class="info-box">
                    <strong>🏗️ Architecture Notes:</strong><br>
                    • <strong>Control Plane Certificates:</strong> Managed by the hosting cluster, not visible here<br>
                    • <strong>Worker Node Certificates:</strong> Visible certificates for workloads and operators<br>
                    • <strong>Service Certificates:</strong> Automatically managed by service-ca operator<br>
                    • <strong>Router Certificates:</strong> Ingress and application routing certificates
                </div>
                
                <div class="success-box">
                    <strong>🔄 Certificate Rotation:</strong><br>
                    📅 Service CA: Rotates automatically based on operator policies<br>
                    📅 Monitoring: Metrics and alerting certificates<br>
                    📅 Router: Ingress controller certificates<br>
                    📅 Console: Web console access certificates
                </div>
            </div>

            <div class="refresh-info">
                <p>🔄 Page auto-refreshes every 60 seconds | Last updated: $(date)</p>
                <p>💾 Running on Persistent Volume with Certificate Monitoring</p>
                <p>🌐 Monitoring visible certificates in hosted cluster worker nodes</p>
            </div>
        </div>
    </body>
    </html>
    EOF
    }

    # Function to get certificate summary
    get_certificate_summary() {
        cat >> "$OUTPUT_FILE" << 'EOF'
            <div class="section">
                <h2>📊 Certificate Summary</h2>
                <div class="cert-summary">
    EOF

        local total_certs=0
        local healthy_certs=0
        local warning_certs=0
        local critical_certs=0

        # Count certificates across all namespaces
        while read namespace name type age; do
            if [ -n "$namespace" ] && [ -n "$name" ]; then
                total_certs=$((total_certs + 1))
                
                # Get certificate data and check expiry
                cert_data=$(oc -n $namespace get secret $name -o go-template='{{index .data "tls.crt"}}' 2>/dev/null)
                if [ -n "$cert_data" ]; then
                    not_after=$(echo "$cert_data" | base64 -d 2>/dev/null | openssl x509 -noout -enddate 2>/dev/null | cut -d= -f2)
                    if [ -n "$not_after" ]; then
                        expiry_epoch=$(date -d "$not_after" +%s 2>/dev/null)
                        current_epoch=$(date +%s)
                        days_left=$(( (expiry_epoch - current_epoch) / 86400 ))

                        if [ $days_left -lt 30 ]; then
                            critical_certs=$((critical_certs + 1))
                        elif [ $days_left -lt 90 ]; then
                            warning_certs=$((warning_certs + 1))
                        else
                            healthy_certs=$((healthy_certs + 1))
                        fi
                    fi
                fi
            fi
        done < <(oc get secrets -A --no-headers 2>/dev/null | grep kubernetes.io/tls)

        cat >> "$OUTPUT_FILE" << EOF
                    <div class="summary-card">
                        <h3>Total Certificates</h3>
                        <div class="summary-count" style="color: #3498db;">$total_certs</div>
                    </div>
                    <div class="summary-card">
                        <h3>Healthy</h3>
                        <div class="summary-count" style="color: #2ecc71;">$healthy_certs</div>
                    </div>
                    <div class="summary-card">
                        <h3>Warning</h3>
                        <div class="summary-count" style="color: #f39c12;">$warning_certs</div>
                    </div>
                    <div class="summary-card">
                        <h3>Critical</h3>
                        <div class="summary-count" style="color: #e74c3c;">$critical_certs</div>
                    </div>
                </div>
            </div>
    EOF
    }

    # Function to check certificates in a namespace
    check_namespace_certs() {
        local namespace=$1
        local title=$2

        cat >> "$OUTPUT_FILE" << EOF
            <div class="section">
                <h2>🔐 $title</h2>
    EOF

        # Check if namespace exists
        if ! oc get namespace "$namespace" >/dev/null 2>&1; then
            cat >> "$OUTPUT_FILE" << EOF
                <div class="alert-box">⚠️ Namespace $namespace not found</div>
            </div>
    EOF
            return
        fi

        cat >> "$OUTPUT_FILE" << 'EOF'
                <table class="cert-table">
                    <tr>
                        <th>Certificate Name</th>
                        <th>Age</th>
                        <th>Expires In</th>
                        <th>Subject</th>
                        <th>Status</th>
                    </tr>
    EOF

        local cert_found=false
        # Get TLS secrets in this namespace
        oc -n $namespace get secrets --no-headers 2>/dev/null | grep kubernetes.io/tls | while read name type data age; do
            cert_found=true
            
            # Get the certificate data
            cert_data=$(oc -n $namespace get secret $name -o go-template='{{index .data "tls.crt"}}' 2>/dev/null)
            
            if [ -n "$cert_data" ]; then
                # Try to decode and get certificate info
                cert_decoded=$(echo "$cert_data" | base64 -d 2>/dev/null)
                
                if [ -n "$cert_decoded" ]; then
                    not_after=$(echo "$cert_decoded" | openssl x509 -noout -enddate 2>/dev/null | cut -d= -f2)
                    subject=$(echo "$cert_decoded" | openssl x509 -noout -subject 2>/dev/null | cut -d= -f2- | sed 's/^subject=//')
                    
                    if [ -n "$not_after" ]; then
                        expiry_epoch=$(date -d "$not_after" +%s 2>/dev/null)
                        current_epoch=$(date +%s)
                        days_left=$(( (expiry_epoch - current_epoch) / 86400 ))

                        # Determine status and color
                        local status_class=""
                        local status_text=""
                        if [ $days_left -lt 30 ]; then
                            status_class="status-critical"
                            status_text="🔴 $days_left days"
                        elif [ $days_left -lt 90 ]; then
                            status_class="status-warning"
                            status_text="🟡 $days_left days"
                        else
                            status_class="status-good"
                            status_text="🟢 $days_left days"
                        fi
                        
                        # Clean up subject for display
                        subject_clean=$(echo "$subject" | sed 's/CN=//g' | cut -c1-40)
                    else
                        status_class="status-warning"
                        status_text="🟡 Parse error"
                        subject_clean="Unknown"
                    fi
                else
                    status_class="status-warning"
                    status_text="🟡 Decode error"
                    subject_clean="Unknown"
                fi
            else
                status_class="status-warning"
                status_text="🟡 No data"
                subject_clean="Unknown"
            fi

            cat >> "$OUTPUT_FILE" << EOF
                    <tr class="$status_class">
                        <td>$name</td>
                        <td>$age</td>
                        <td>$status_text</td>
                        <td>$subject_clean</td>
                        <td>$status_text</td>
                    </tr>
    EOF
        done

        if [ "$cert_found" = false ]; then
            cat >> "$OUTPUT_FILE" << 'EOF'
                    <tr><td colspan="5" style="text-align: center; color: #f39c12;">⚠️ No TLS certificates found in this namespace</td></tr>
    EOF
        fi

        cat >> "$OUTPUT_FILE" << 'EOF'
                </table>
            </div>
    EOF
    }

    # Generate the HTML output
    generate_html_output
    
    echo "Certificate status HTML generated at: $OUTPUT_FILE" 