apiVersion: v1
kind: Namespace
metadata:
  name: cert-status-app
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-checker-script
  namespace: cert-status-app
data:
  check-certs.sh: |
    #!/bin/bash
    set -e
    
    # Create HTML file
    cat > /var/www/html/certs.html << 'EOF'
    <!DOCTYPE html>
    <html>
    <head>
        <title>Certificate Status Monitor</title>
        <meta http-equiv="refresh" content="30">
        <style>
            body { font-family: Arial, sans-serif; margin: 20px; background-color: #f5f5f5; }
            .container { max-width: 1200px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { padding: 8px; border-bottom: 1px solid #ddd; text-align: left; }
            th { background-color: #f8f9fa; font-weight: bold; }
            tr:hover { background-color: #f9f9f9; }
            h1 { color: #151515; margin: 0; }
            h2 { color: #0066cc; margin-top: 0; }
            .status-ok { color: #28a745; }
            .status-warning { color: #ffc107; }
            .status-error { color: #dc3545; }
            .status-rotation { color: #17a2b8; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Certificate Status Monitor</h1>
            <p>Last updated: <span id="timestamp"></span></p>
            <table>
                <thead>
                    <tr>
                        <th>Namespace</th>
                        <th>Certificate</th>
                        <th>Created</th>
                        <th>Expires</th>
                        <th>Days Left</th>
                        <th>Status</th>
                        <th>Refresh Period</th>
                    </tr>
                </thead>
                <tbody id="certTable">
                </tbody>
            </table>
        </div>
        <script>
            document.getElementById('timestamp').textContent = new Date().toLocaleString();
        </script>
    </body>
    </html>
    EOF
    
    # Function to check certificates in a namespace
    check_namespace_certs() {
        local namespace="$1"
        local current_epoch=$(date +%s)
        
        # Get TLS secrets in this namespace
        while IFS= read -r line; do
            if [[ -z "$line" ]]; then continue; fi
            
            local name=$(echo "$line" | awk '{print $1}')
            
            # Fetch potential cert data
            local cert_data=$(oc -n "$namespace" get secret "$name" -o go-template='{{index .data "tls.crt"}}' 2>/dev/null)
            if [[ -z "$cert_data" ]]; then
                cert_data=$(oc -n "$namespace" get secret "$name" -o go-template='{{index .data "ca.crt"}}' 2>/dev/null)
            fi
            
            # Skip secrets without cert material
            if [[ -z "$cert_data" ]]; then
                continue
            fi
            
            if [[ -n "$cert_data" ]]; then
                local cert_decoded=$(echo "$cert_data" | base64 -d 2>/dev/null)
                
                if [[ -n "$cert_decoded" ]]; then
                    local not_before=$(echo "$cert_decoded" | openssl x509 -noout -startdate 2>/dev/null | cut -d= -f2)
                    local not_after=$(echo "$cert_decoded" | openssl x509 -noout -enddate 2>/dev/null | cut -d= -f2)
                    
                    if [[ -n "$not_before" && -n "$not_after" ]]; then
                        # Parse dates
                        local before_epoch=$(date -j -f "%b %d %H:%M:%S %Y %Z" "$not_before" +%s 2>/dev/null)
                        local after_epoch=$(date -j -f "%b %d %H:%M:%S %Y %Z" "$not_after" +%s 2>/dev/null)
                        
                        if [[ -z "$before_epoch" || -z "$after_epoch" ]]; then
                            before_epoch=$(date -j -f "%b  %d %H:%M:%S %Y %Z" "$not_before" +%s 2>/dev/null)
                            after_epoch=$(date -j -f "%b  %d %H:%M:%S %Y %Z" "$not_after" +%s 2>/dev/null)
                        fi
                        
                        if [[ -n "$before_epoch" && -n "$after_epoch" ]]; then
                            # Calculate status
                            local days_until_expiry=$(( (after_epoch - current_epoch) / 86400 ))
                            local total_lifespan=$((after_epoch - before_epoch))
                            local lifespan_days=$((total_lifespan / 86400))
                            local rotation_epoch=$((before_epoch + (total_lifespan * 80 / 100)))
                            local days_until_rotation=$(( (rotation_epoch - current_epoch) / 86400 ))
                            
                            # Format dates
                            local created_date=$(date -j -f "%b %d %H:%M:%S %Y %Z" "$not_before" "+%m/%d/%Y" 2>/dev/null || date -j -f "%b  %d %H:%M:%S %Y %Z" "$not_before" "+%m/%d/%Y" 2>/dev/null || echo "Unknown")
                            local expiry_date=$(date -j -f "%b %d %H:%M:%S %Y %Z" "$not_after" "+%m/%d/%Y" 2>/dev/null || date -j -f "%b  %d %H:%M:%S %Y %Z" "$not_after" "+%m/%d/%Y" 2>/dev/null || echo "Unknown")
                            
                            # Get refresh period
                            local refresh_period=$(oc -n "$namespace" get secret "$name" -o jsonpath='{.metadata.annotations.certificates\.openshift\.io/refresh-period}' 2>/dev/null)
                            if [[ -z "$refresh_period" ]]; then
                                refresh_period="not set"
                            fi
                            
                            # Determine status
                            local status=""
                            local status_class=""
                            if [[ "$days_until_expiry" -lt 0 ]]; then
                                status="EXPIRED"
                                status_class="status-error"
                            elif [[ "$days_until_expiry" -lt 30 ]]; then
                                status="EXPIRING"
                                status_class="status-warning"
                            elif [[ "$days_until_rotation" -lt 0 ]]; then
                                status="ROTATION DUE"
                                status_class="status-rotation"
                            else
                                status="OK"
                                status_class="status-ok"
                            fi
                            
                            # Add row to HTML table
                            echo "                    <tr>" >> /var/www/html/certs.html
                            echo "                        <td>$namespace</td>" >> /var/www/html/certs.html
                            echo "                        <td>$name</td>" >> /var/www/html/certs.html
                            echo "                        <td>$created_date</td>" >> /var/www/html/certs.html
                            echo "                        <td>$expiry_date</td>" >> /var/www/html/certs.html
                            echo "                        <td>$days_until_expiry</td>" >> /var/www/html/certs.html
                            echo "                        <td class=\"$status_class\">$status</td>" >> /var/www/html/certs.html
                            echo "                        <td>$refresh_period</td>" >> /var/www/html/certs.html
                            echo "                    </tr>" >> /var/www/html/certs.html
                        fi
                    fi
                fi
            fi
        done <<EOF
$(oc -n "$namespace" get secrets --no-headers -o custom-columns="NAME:.metadata.name" 2>/dev/null)
EOF
    }
    
    # Check important certificate namespaces
    for namespace in "openshift-etcd" "openshift-kube-apiserver" "openshift-authentication" "openshift-image-registry" "kube-system" "openshift-node" "openshift-service-ca" "openshift-ingress" "openshift-monitoring" "openshift-console" "openshift-ovn-kubernetes" "openshift-machine-config-operator"; do
        if oc get namespace "$namespace" >/dev/null 2>&1; then
            check_namespace_certs "$namespace"
        fi
    done
    
    # Close the tbody tag
    echo "                </tbody>" >> /var/www/html/certs.html
    echo "            </table>" >> /var/www/html/certs.html
    echo "        </div>" >> /var/www/html/certs.html
    echo "    </body>" >> /var/www/html/certs.html
    echo "</html>" >> /var/www/html/certs.html

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-status-app
  namespace: cert-status-app
  labels:
    app: cert-status-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-status-monitor
  template:
    metadata:
      labels:
        app: cert-status-monitor
    spec:
      serviceAccountName: cert-monitor-sa
      containers:
      - name: httpd
        image: registry.redhat.io/rhel8/httpd-24:latest
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: html-content
          mountPath: /var/www/html
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      - name: cert-updater
        image: registry.redhat.io/openshift4/ose-cli:latest
        command: ["/bin/bash"]
        args:
        - -c
        - |
          set -e
          chmod +x /scripts/check-certs.sh
          while true; do
            /scripts/check-certs.sh
            sleep 300
          done
        volumeMounts:
        - name: cert-checker-script
          mountPath: /scripts
        - name: html-content
          mountPath: /var/www/html
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      volumes:
      - name: html-content
        emptyDir: {}
      - name: cert-checker-script
        configMap:
          name: cert-checker-script
          defaultMode: 0755
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cert-monitor-sa
  namespace: cert-status-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-monitor-role
rules:
- apiGroups: [""]
  resources: ["secrets", "namespaces"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cert-monitor-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-monitor-role
subjects:
- kind: ServiceAccount
  name: cert-monitor-sa
  namespace: cert-status-app
---
apiVersion: v1
kind: Service
metadata:
  name: cert-status-service
  namespace: cert-status-app
  labels:
    app: cert-status-monitor
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: cert-status-monitor
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cert-status-route
  namespace: cert-status-app
  labels:
    app: cert-status-monitor
spec:
  to:
    kind: Service
    name: cert-status-service
  port:
    targetPort: 8080