apiVersion: v1
kind: Namespace
metadata:
  name: hello-world-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: hello-world-test
  labels:
    app: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: html-content
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-content
        configMap:
          name: hello-world-content
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-content
  namespace: hello-world-test
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Hello World Test</title>
    </head>
    <body>
        <h1>Hello World!</h1>
        <p>This is a test application to verify routing is working.</p>
        <p>Current time: <script>document.write(new Date());</script></p>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hello-world-test
  labels:
    app: hello-world
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: hello-world
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-world-route
  namespace: hello-world-test
  labels:
    app: hello-world
spec:
  to:
    kind: Service
    name: hello-world-service
  port:
    targetPort: 80